### PR TITLE
[network][discovery] Fix #587. Incl seed addrs in connmgr update

### LINKED ISSUE #587: Cluster discovery seem to break if first connected peer give list of wrong IPs
We had situation in cluster test, when it partitioned into 2 independent sub-clusters with 86 and 14 machines. Machines in those sub-clusters could connect to each other, but did not see machines outside of sub-cluster.

Validators in smaller (14 machines) cluster had correct seed peer config file, pointing to machines in bigger cluster, however they did not try to connect to them. Instead they assumed, for some reason, wrong IP addresses for those seed peers.

I restarted one machine in smaller sub-cluster, but it still was not able to reconnect to bigger sub-cluster. It seems that one of other machines in smaller group sent it wrong IP addresses before this machine tried using seed peers.

Once I restarted all machines in small sub-cluster simultaneously, they was able to recover and reconnect with everyone else.

cc @0-o-0

### PR DESCRIPTION
**Pull request by phlip9**
+ In this change, we _append_ our configured seed peer addrs to
whatever addrs we learn through discovery for that seed peer. This
prevents a stale discovery note from clobbering a fresh seed peer
configuration, which lead to the parition identified in #587.

### CODE REVIEW

File: network/src/protocols/discovery/mod.rs [hunk 1]
```diff
@@ -169,9 +169,8 @@ where
                     peer_info
                         .get_addrs()
                         .iter()
-                        .map(|addr| {
-                            Multiaddr::try_from(addr.clone()).expect("Multiaddr parsing failed")
-                        })
+                        .cloned()
```
Comment (davidiw) [inline network/src/protocols/discovery/mod.rs]: Why do we need the cloning here?

File: network/src/protocols/discovery/mod.rs [hunk 2]
```diff
@@ -357,18 +356,26 @@ where
                     assert_ne!(peer_id, self_peer_id);
                     // Update internal state of the peer with new Note.
                     self.known_peers.insert(peer_id, (peer_info.clone(), note));
+
+                    // The multiaddrs in the peer's discovery Note.
+                    let mut peer_addrs: Vec<Multiaddr> = peer_info
+                        .get_addrs()
+                        .iter()
+                        .cloned()
```
Comment (davidiw) [inline network/src/protocols/discovery/mod.rs]: same, do we need this?

File: network/src/protocols/discovery/mod.rs [hunk 3]
```diff
@@ -357,18 +356,26 @@ where
...
+                        .map(|addr| Multiaddr::try_from(addr).expect("Multiaddr parsing fails"))
+                        .collect();
+
+                    // Append the addrs in the seed PeerInfo if this peer is
+                    // configured as one of our seed peers.
+                    if let Some(seed_info) = self.seed_peers.get(&peer_id) {
+                        let seed_addrs_iter = seed_info.get_addrs().iter().cloned().map(|addr| {
+                            Multiaddr::try_from(addr).expect("Multiaddr parsing fails")
```
Comment (davidiw) [inline network/src/protocols/discovery/mod.rs]: expect results in a panic. This makes it easy for a remote validator to crash all other validators. We should not have expect used after the run time has started unless there is some truly unrecoverable behavior.

File: network/src/protocols/discovery/test.rs [hunk 4]
```diff
@@ -29,10 +29,28 @@ fn gen_full_node_payload() -> FullNodePayload {
     payload
 }
 
+fn get_addrs_from_note(note: &Note) -> Vec<Multiaddr> {
+    let signed_peer_info = note.get_signed_peer_info();
+    let peer_info: PeerInfo = protobuf::parse_from_bytes(signed_peer_info.get_peer_info()).unwrap();
```
Comment (davidiw) [inline network/src/protocols/discovery/test.rs]: unwrap in a test is probably okay, but prefer expect so you get a sensible error message.

File: network/src/protocols/discovery/test.rs [hunk 5]
```diff
@@ -317,9 +338,91 @@ fn outbound() {
...
 
     rt.block_on(f_peer_mgr.boxed().unit_error().compat())
         .unwrap();
 }
+
+#[test]
+fn addr_update_includes_seed_addrs() {
+    ::logger::try_init_for_testing();
+    let mut rt = Runtime::new().unwrap();
+    // Setup self.
```
Comment (davidiw) [inline network/src/protocols/discovery/test.rs]: maybe insert a new line before this to improve readability

File: network/src/protocols/discovery/test.rs [hunk 6]
```diff
@@ -317,9 +338,91 @@ fn outbound() {
...
+    let peer_id = PeerId::random();
+    let addrs = vec![Multiaddr::from_str("/ip4/127.0.0.1/tcp/9090").unwrap()];
+    let (self_pub_keys, self_signer) = generate_network_pub_keys_and_signer(peer_id);
+    // Setup seed.
```
Comment (davidiw) [inline network/src/protocols/discovery/test.rs]: maybe insert a new line before this to improve readability

File: network/src/protocols/discovery/test.rs [hunk 7]
```diff
@@ -317,9 +338,91 @@ fn outbound() {
...
+    let mut seed_peer_addrs = get_addrs_from_info(&seed_peer_info);
+    let seed_peer_payload = gen_full_node_payload();
+    let seed_peer_id = PeerId::random();
+    let (seed_pub_keys, seed_signer) = generate_network_pub_keys_and_signer(seed_peer_id);
+    let trusted_peers = Arc::new(RwLock::new(
+        vec![(seed_peer_id, seed_pub_keys), (peer_id, self_pub_keys)]
+            .into_iter()
+            .collect(),
+    ));
+    // Setup discovery.
```
Comment (davidiw) [inline network/src/protocols/discovery/test.rs]: maybe insert a new line before this to improve readability

File: network/src/protocols/discovery/test.rs [hunk 8]
```diff
@@ -317,9 +338,91 @@ fn outbound() {
...
+        // note addrs and the original configured seed addrs.
+        expect_address_update(
+            &mut conn_mgr_reqs_rx,
+            seed_peer_id,
+            &expected_seed_addrs[..],
+        )
+        .await;
+    };
+    rt.block_on(f_peer_mgr.boxed().unit_error().compat())
+        .unwrap();
```
Comment (davidiw) [inline network/src/protocols/discovery/test.rs]: if you didn't modify the old code, would this fail here?

(this code is foreign to me, would like to understand how this test is actually being evaluated)

Comment (phlip9) [reply network/src/protocols/discovery/test.rs]: Yep! Without the changes in `discovery/mod.rs`, this line:

```rust
// L419:
expect_address_update(
    &mut conn_mgr_reqs_rx,
    seed_peer_id,
    &expected_seed_addrs[..],
)
.await;
```

would fail, since the seed peer addresses would not be included in the `UpdateAddresses` message sent to the (mocked) connectivity manager.

File: network/src/protocols/discovery/test.rs (hunk 5 above)
Comment (phlip9) [reply network/src/protocols/discovery/test.rs]: Ahh, I was mostly copying @bothra90 's style of the surround tests. But I agree; I prefer more new lines.

File: network/src/protocols/discovery/test.rs (hunk 4 above)
Comment (phlip9) [reply network/src/protocols/discovery/test.rs]: Hmm, I'm not sure how I feel about this. My knee jerk reaction is that this seems noisy and low-value, since this is neither test related nor (realistically) error-able (assuming our protobuf library can read its own serialized output).

I'm probably wrong though :)

/cc @bothra90 ?

File: network/src/protocols/discovery/mod.rs [hunk 9]
```diff
@@ -357,18 +356,26 @@ where
                     assert_ne!(peer_id, self_peer_id);
                     // Update internal state of the peer with new Note.
                     self.known_peers.insert(peer_id, (peer_info.clone(), note));
+
+                    // The multiaddrs in the peer's discovery Note.
+                    let mut peer_addrs: Vec<Multiaddr> = peer_info
```
Comment (bothra90) [inline network/src/protocols/discovery/mod.rs]: @phlip9 Should we create a function to get `Vec<Multiaddr>` from `PeerInfo`?

File: network/src/protocols/discovery/mod.rs (hunk 3 above)
Comment (bothra90) [reply network/src/protocols/discovery/mod.rs]: @phlip9: definitely agree with the idea of separating unverified structs from verified ones -- [`bytecode_verifier`](https://github.com/libra/libra/blob/112cb1e7a5d81b90b191e2598620e3bcf1f4241a/language/bytecode_verifier/src/verifier.rs#L30-L34) uses type level state machines to encode invariants. Might be worth taking a look.

File: network/src/protocols/discovery/test.rs (hunk 4 above)
Comment (bothra90) [reply network/src/protocols/discovery/test.rs]: Yeah, I don't see much value from adding an expect as compared to an unwrap here

File: network/src/protocols/discovery/mod.rs (hunk 9 above)
Comment (phlip9) [reply network/src/protocols/discovery/mod.rs]: I think this should be a member of the "verified" struct
