### PR TITLE
[libra node] Initialize network module after consensus

### LINKED ISSUE #749: [Bug] consensus stuck after restart and resume state sync
# 🐛 Bug

## To reproduce

** Stack trace/error message **
```
nightly-bench-4 validator-1e5d5a74/validator/d0b54f9991cb48d094245d55d9258844 I0828 08:43:29.287941 140506868741888 consensus/src/chained_bft/persistent_storage.rs:374] Consensus recovery done but additional state synchronization is required.
....
nightly-bench-4 validator-1e5d5a74/validator/d0b54f9991cb48d094245d55d9258844 I0828 08:43:31.161557 140506868741888 network/src/peer_manager/mod.rs:443] Inbound connection with peer ab0d6a54 established
nightly-bench-4 validator-1e5d5a74/validator/d0b54f9991cb48d094245d55d9258844 I0828 08:43:33.834076 140506868741888 network/src/peer_manager/mod.rs:443] Inbound connection with peer 57ff8374 established
nightly-bench-4 validator-1e5d5a74/validator/d0b54f9991cb48d094245d55d9258844 I0828 08:43:34.243086 140506868741888 network/src/connectivity_manager/mod.rs:216] Should be connected to peer: 8deeeaed at addr(s): ********
nightly-bench-4 validator-1e5d5a74/validator/d0b54f9991cb48d094245d55d9258844 I0828 08:43:34.243144 140506868741888 network/src/connectivity_manager/mod.rs:240] Will dial peer: 8deeeaed after 2s
nightly-bench-4 validator-1e5d5a74/validator/d0b54f9991cb48d094245d55d9258844 I0828 08:43:34.524315 140506868741888 network/src/protocols/discovery/mod.rs:350] Received updated note for peer: 8deeeaed from peer: 57ff8374
nightly-bench-4 validator-1e5d5a74/validator/d0b54f9991cb48d094245d55d9258844 I0828 08:43:34.524367 140506868741888 network/src/protocols/discovery/mod.rs:350] Received updated note for peer: 57ff8374 from peer: 57ff8374
nightly-bench-4 validator-1e5d5a74/validator/d0b54f9991cb48d094245d55d9258844 I0828 08:43:34.524390 140506868741888 network/src/protocols/discovery/mod.rs:350] Received updated note for peer: ab0d6a54 from peer: 57ff8374
nightly-bench-4 validator-1e5d5a74/validator/d0b54f9991cb48d094245d55d9258844 I0828 08:43:34.998099 140506868741888 network/src/peer_manager/mod.rs:443] Inbound connection with peer 8deeeaed established
nightly-bench-4 validator-1e5d5a74/validator/d0b54f9991cb48d094245d55d9258844 I0828 08:43:34.998150 140506868741888 network/src/connectivity_manager/mod.rs:339] Cancelled pending dial to peer: 8deeeaed
```

## Expected Behavior

We initiate a state sync upon restart and the system got stuck. From the log, the current guess is networking failed to setup connections. We expect:
- better error message, it's not very clear why the system is stuck.
- handle the network startup gracefully

### PR DESCRIPTION
**Pull request by bothra90**
This diff fixes #749.

The order in which network provider, consensus and state synchronizer were initialized was creating a deadlock. We were initializing network provider after consensus, which was getting blocked on state synchronizer to catch up to root ledger info. The state synchronizer was in turn blocked because network provider had not delivered any NewPeer messages for it to know who to sync from -- network provider could not deliver these messages because it was not even initialized, hence creating a deadlock.

We fix the deadlock by starting network provider before consensus.

### Have you read the [Contributing Guidelines on pull requests](https://github.com/libra/libra/blob/master/CONTRIBUTING.md#pull-requests)?

Yes

### CODE REVIEW

File: libra_node/src/main_node.rs [hunk 1]
```diff
@@ -259,12 +260,26 @@ pub fn setup_environment(node_config: &mut NodeConfig) -> (AdmissionControlClien
         ));
         debug!("Mempool started in {} ms", instant.elapsed().as_millis());
 
-        instant = Instant::now();
+        // Start the network provider.
+        // Note: We need to start network provider before consensus, because the consensus
+        // initializtion is blocked on state synchronizer to sync to the initial root ledger info,
```
Comment (aching) [inline libra_node/src/main_node.rs]:
```suggestion
        // initialization is blocked on state synchronizer to sync to the initial root ledger info,
```

File: libra_node/src/main_node.rs [hunk 2]
```diff
@@ -274,15 +289,16 @@ pub fn setup_environment(node_config: &mut NodeConfig) -> (AdmissionControlClien
         consensus_provider
             .start()
             .expect("Failed to start consensus. Can't proceed.");
+
```
Comment (aching) [inline libra_node/src/main_node.rs]: nit: Random extra line?  Feel free to ignore though.

File: libra_node/src/main_node.rs [hunk 3]
```diff
@@ -259,12 +260,26 @@ pub fn setup_environment(node_config: &mut NodeConfig) -> (AdmissionControlClien
...
         debug!("Mempool started in {} ms", instant.elapsed().as_millis());
 
-        instant = Instant::now();
+        // Start the network provider.
+        // Note: We need to start network provider before consensus, because the consensus
+        // initialization is blocked on state synchronizer to sync to the initial root ledger info,
+        // which in turn cannot make progress before network initialization because the NewPeer
+        // events which state synchronizer uses to know its peers are delivered by network provider.
+        // If we were to start network provider after consensus, we create a cyclic dependency from
+        // network provider -> consensus -> state synchronizer -> network provier. This deadlock was
```
Comment (mimoo) [inline libra_node/src/main_node.rs]: typo "provier"
